print("Введите первое число")
a = int(input())
print("Введите второе число")
d = int(input())

print(a, "+", d, "=", a+d)
print(a, "-", d, "=", a-d)
print(d, "-", a, "=", d-a)
print(a, "*", d, "=", a*d)
print(a, "/", d, "=", a/d)
print(d, "/", a, "=", d/a)
print(a, "^", d, "=", a**d)
print(d, "^", a, "=", d**a)